<a href="https://colab.research.google.com/github/OhaN2k/diveintocode-ml/blob/master/Mathematics_for_Machine_Learning_Pre_Class_assignment_3_Matrix_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# [Problem 1] Matrix product is calculated manually
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = np.array([[6, 29, -20], [12, 52, 38], [-18, -51, -48]])

The product of matrix A and B is 3x3.
We get the number at position [0, 0] by multiplying the each value of the first row of matrix A with each value of the first column of matrix B, then take sum of those numbers. Similarly, number at [0, 1] = row 1A * column 2B,... number at [2, 2] = row 3A * column 3B.

In [18]:
# [Problem 2] Calculation by NumPy function
print(np.dot(a_ndarray, b_ndarray))
print(np.matmul(a_ndarray, b_ndarray))
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [36]:
# [Problem 3] Implementation of calculation of a certain element
import numpy as np
def v_product(v1, v2):
  return np.sum(v1*v2)

# [Problem 4] Creating a function that performs matrix multiplication
def matrix_mul(m1, m2):
  if len(m1[0]) != len(m2):
    print("Invalid matrix dimension!")
    return
  m3 = np.zeros((len(m1), len(m2[0])))
  for i in range(len(m1)):
    for j in range(len(m2[0])):
      m3[i][j] = v_product(m1[i], m2.T[j])
  return m3

m = matrix_mul(a_ndarray, b_ndarray)
print(m)

# [Problem 6] Transposition
print(m.T)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
[[  6.  12. -18.]
 [ 29.  52. -51.]
 [-20.  38. -48.]]


In [35]:
# [Problem 5] Judge the input whose calculation is not defined
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
f = matrix_mul(d_ndarray, e_ndarray)

Invalid matrix dimension!
